version: '3'
services:
  db:
    image: mysql:8.0.13
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: game
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/MYSQL_DATABASE
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
